### ISSUE TITLE
Heroku Deploy Fatal Error

### ISSUE THREAD

**Issue by kavehcito** [absalomedia/prestashop-12-factor#4]
Hello - 

I'm trying to deploy to Heroku, and I'm getting this error:

```
PHP Fatal error:  Cannot use lexical variable $eventName as a parameter name in /app/vendor/guzzlehttp/guzzle/src/Event/Emitter.php on line 48
[37;41mScript prestashop new store --release=1.7.1.0 --fixture=starwars handling the prestashop-setup-core event returned with error code 255[39;49m
```

**Comment by absalomedia** [comment]
Looks to be a Guzzle dependency issue (5.3 & below) on the Prestashop Installer package.

Upline package developer has recognised it's a [known issue](https://github.com/gskema/prestashop-installer/issues/12)

Once they can release an update resolving their Guzzle dependencies, this issue will be resolved.

**Comment by beckah** [comment]
Hit the same issue:
```
prestashop new store --release=1.7.1.0 --fixture=starwars
Creating PrestaShop application...
Downloading from URL: http://www.prestashop.com/download/releases/prestashop_1.7.1.0.zip
PHP Fatal error:  Cannot use lexical variable $eventName as a parameter name in /app/vendor/guzzlehttp/guzzle/src/Event/Emitter.php on line 48
[37;41mScript prestashop new store --release=1.7.1.0 --fixture=starwars handling the prestashop-setup-core event returned with error code 255[39;49m
```

**Comment by krzysiekpiasecki** [comment]
This bug has been fixed with PR https://github.com/gskema/prestashop-installer/pull/15.

Issue: https://github.com/gskema/prestashop-installer/issues/12

**Comment by absalomedia** [comment]
Looks like Heroku no longer uses the 'name' variable, but 'title' instead.  Fixed with latest commit

**Comment by krzysiekpiasecki** [comment]
@absalomedia Please reopen the ticket, because the exception still occurs 

```
[37;41m  [Symfony\Component\Console\Exception\RuntimeException]  [39;49m
[37;41m  The "--title" option does not exist.                    [39;49m
```

Did you make a successful deploy to heroku?

**Comment by rafaelblink** [comment]
In app.json

If You add -- before the title, works!

"postdeploy": "composer prestashop-setup-core  &&  composer prestashop-db-core **--** --title='Prestashop on Heroku' --domain=example.herokuapp.com --db_server= --db_name=prestashop --db_user=\"$PRESTASHOP_ADMIN_USER\" --db_password=\"$PRESTASHOP_ADMIN_PASSWORD\" --email=\"$PRESTASHOP_ADMIN_EMAIL\" && composer prestashop-setup-clean && composer prestashop-setup-welcome "

But new exception accurs :(

Script php store/install/install_cli.php handling the prestashop-db-core event returned with error code 1

**Comment by absalomedia** [comment]
Hey @rafaelblink the CLI interface has changed inside Prestashop. I've now fixed it without needing to update the branch

**Comment by rafaelblink** [comment]
Hey @absalomedia, the exception continues 🤕 

`[37;41m                                                          [39;49m
[37;41m  [Symfony\Component\Console\Exception\RuntimeException]  [39;49m
[37;41m  The "--name" option does not exist.                     [39;49m
[37;41m                                                          [39;49m
`

**Comment by VioletaCalvo** [comment]
Same error here `The "--name" option does not exist.`have you found the solution?

**Comment by rafaelblink** [comment]
My solution was make deploy on amazon :joy: :joy: :joy: :joy: :joy: :joy: :joy: :joy:

**Comment by mric111** [comment]
What's the solution plse ?
